# Chapter 2 - Linear Algebra:

## The following notebook is based on the \*Mathematics For Machine Learning\* textbook written by:
*   Marc Peter Deisenroth
*   A. Aldo Faisal
*   Cheng Soon Ong

## What does this notebook contain?
*   It contains all the concepts from this book written in Python Code.

# What is a Linear Algebra?
*   Linear Algebra is the study of Vectors and certain rules to manipulate Vectors.


# What is a Vector?
*   Vector is an object that can be added together and multiplied by scalars to produce another object of the same kind.
*   Any object satisfying this condition is considered a Vector.
*   Eg:-
    * Geometric vectors
    * Polynomials
    * Audio Signals
    * Elements of $R^n$ (tuples of *n* real numbers)

# One major concept in Mathematics is the idea of *Closure*:
* This is basically asking a question: - *What is the set of all things that can result from our proposed solution?*
* In the case of Vectors: - *What is the set of Vectors that can result by starting with a small set of vectors, and adding them to each other and scaling them?*
    *   This results in: - **Vector Space**

# 2.1 Systems of Linear Equation:

## Geometric Interpretation of Systems of Linear Equations
* Let us consider a system of linear equations with two variables $x_1$, $x_2$.
* Each linear equation defines a line on the $x_1$,$x_2$-plane.
* The **solution** to a system of linear equations must satisfy all equations simultaneously. However, the **solution set** is the intersection of these lines.
* The intersection set can be:
    * line (when the lines overlap)
    * a point (only one point of intersection)
    * or empty (when lines are parallel)
* A systematic approach for solving **systems of linear equations** that contains higher number of variables is to collect all the variables, coefficient & outputs into **Vectors** and then represent them in **Matrices**.

# 2.2 Matrices:

In [5]:
# Simple Representation of 2x3 Matrix using Arrays:
import numpy as np

A = np.array([[1,2,3],
             [4,5,6]])
print(A)


[[1 2 3]
 [4 5 6]]


# 2.2.1 Matrix Addition & Multiplication

## Addition of two Matrices is defined as the element wise sum:

In [8]:
# Define two Matrix A & B and then perform addition:
import numpy as np

A = np.array([[10,20],[11,22]])
B = np.array([[30,40],[33,44]])
C = A + B
print(f"Matrix A is: {A}")
print(f"Matrix B is: {B}")
print(f"Sum of Matrix A & B is: {C}")

Matrix A is: [[10 20]
 [11 22]]
Matrix B is: [[30 40]
 [33 44]]
Sum of Matrix A & B is: [[40 60]
 [44 66]]


## Whereas in Multiplication of two Matrices:
* The neighbouring dimensions should match.
    * i.e If matrix A is m$\times$n then it can only multiply with a matrix with dimension n$\times$k
* Then we multiply the element of the *m*th row of A with *k*th column of B and sum them up

## Matrix Multiplication Properties:
* It is **Not Commutative**, i.e AB $\neq$ BA
* It is **Associative**, i.e (AB)C = A(BC)
* It is **Distributive**, i.e (A+B)C = AC + BC
* Multiplication with **Identity** matrix, i.e $I_n$A = A$I_n$ = A
    *   identity Matrix is the one in which all the elements are 0 except the diagonals which are 1.

In [31]:
# Define two Matrix A & B and then perform multiplication:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[6,7],[8,9],[10,11]])
C = A @ B # In Python if we want to Multiply two Array as Matrix Multiplication we should use @ instead of *
print(f"Matrix A is: \n {A}")
print(f"Matrix B is: \n {B}")
print(f"Mulitplication of AB is: \n {C}")

# This operation will result in Hadamard Product in which the elementwise Multiplication is happening
# But this code will give us an error as for Hadamard Product the dimensions of both the Matrices should be same.
#D = A * B
#print(f"Hadamard Product :  \n {D}")

# It is Not Commutative:
E = B @ A
print(f"Mulitplication of BA is: \n {E}")

# It is Associative:
F = np.array([[3,5,8,2,1],[9,10,4,7,8]])
print(f"(AB)F is: \n {(A @ B) @ F}")
print(f"A(BF) is: \n {A @ (B @ F)}")

Matrix A is: 
 [[1 2 3]
 [4 5 6]]
Matrix B is: 
 [[ 6  7]
 [ 8  9]
 [10 11]]
Mulitplication of AB is: 
 [[ 52  58]
 [124 139]]
Mulitplication of BA is: 
 [[34 47 60]
 [44 61 78]
 [54 75 96]]
(AB)F is: 
 [[ 678  840  648  510  516]
 [1623 2010 1548 1221 1236]]
A(BF) is: 
 [[ 678  840  648  510  516]
 [1623 2010 1548 1221 1236]]


# 2.2.2 Inverse & Transpose:
# Inverse:
* Let us consider a square matrix A.
* Then let us consider another matrix B, which has a property **AB = $I_n$ = BA**
* Then we call the matrix B as the Inverse of A and is represented as **$A^{-1}$**
* Not all matrix has an inverse.
* If a matrix has an inverse, it will be Unique. That matrix will be called *regular/invertible/nonsigular*.
* If a matrix doesn't posses an inverse, it is called *irregular/noninvertible/singular*.


### Example 2.4 (Inverse Matrix)

In [34]:
import numpy as np
from numpy.linalg import inv

A = np.array([[1,2,1],[4,4,5],[6,7,7]])
B = np.array([[-7,-7,6],[2,1,-1],[4,5,-4]])

# Check if B is an Inverse of A
print(f"AB is: \n {A@B}")
print(f"BA is: \n {B@A}")

# Now use the numpy Inverse method to identify the Inverse of A:
print(f"A inverse is : \n {inv(A)}")

AB is: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
BA is: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
A inverse is : 
 [[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


# Transpose:
* For a matrix **A** of dimension m$\times$n and matrix **B** of dimension n$\times$m, if **$B_ij$ = $A_ji$** then **B** is called the transpose of **A**.
* Which can also be written as **B = $A^T$**.